package Components;

import BdConnection.DbConnection;

import javax.swing.JFrame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.Vector;

/**
 * Created by serch on 19/01/15.
 */
public class Compilador extends JFrame{
    private Vector<Regla> R=new Vector();
    private String cond;
    private String Action;
    private String Name;
    private Vector p;
    private SQL sql;
    private DrawArea disp;
    SQListener sqlistener;

    public Compilador(DrawArea disp)
    {
        initComponents();
        sql=new SQL("ejemplo.sql");
        this.disp=disp;

        loadData();

        p=disp.vt;
        //llenarCampos();
        sqlistener=new SQListener(sql,Table1,Att1,Att2,Att3,Att4,Att5,Tables1,disp.TBs,disp.DatabaseMagnament);
        Table1.addItemListener(sqlistener);
        L_Event.setText("Evento e"+disp.cont);
        Events.addItemListener(new MyListener(Events,Att1));
        Events1.addItemListener(new MyListener(Events1,Att4,TF_value4));
        logic_op.addItemListener(new Listener(logic_op,Att1,conditions1,TF_value2));

        ActionListener Listener = new ActionListener() {
            public void actionPerformed(ActionEvent actionEvent)
            {
                boolean select=RB_where.isSelected();
                Att5.setEnabled(select);
                conditions2.setEnabled(select);
                TF_val.setEnabled(select);
            }
        };
        RB_where.addActionListener(Listener);
        disp.Marcar_Regla(disp.cont);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        L_Event = new javax.swing.JLabel();
        L_IF = new javax.swing.JLabel();
        L_THEN = new javax.swing.JLabel();
        Events = new java.awt.Choice();
        Events.add("insert");
        Events.add("delete");
        Events.add("update");
        conditions = new java.awt.Choice();
        TF_value1 = new java.awt.TextField();
        logic_op = new java.awt.Choice();
        conditions1 = new java.awt.Choice();
        Events1 = new java.awt.Choice();
        Events1.add("delete");
        Events1.add("update");
        L_sv = new javax.swing.JLabel();
        L_s = new javax.swing.JLabel();
        RB_where = new javax.swing.JRadioButton();
        conditions2 = new java.awt.Choice();
        TF_val = new javax.swing.JTextField();
        TF_value4 = new javax.swing.JTextField();
        botonS = new javax.swing.JButton();
        TF_value2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Table1 = new java.awt.Choice();
        Att1 = new java.awt.Choice();
        Att2 = new java.awt.Choice();
        Att3 = new java.awt.Choice();
        Tables1 = new javax.swing.JTextField();
        Att4 = new java.awt.Choice();
        Att5 = new java.awt.Choice();
        databaseField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        L_Event.setText("Evento ");

        L_IF.setText("IF");

        L_THEN.setText("THEN");

        Events.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        conditions.add("<");
        conditions.add(">");
        conditions.add("=");
        conditions.add(">=");
        conditions.add("<=");
        conditions.add("!=");
        conditions.add("!>");
        conditions.add("!<");
        conditions.add("<>");

        TF_value1.setText("            ");

        logic_op.add("  ");
        logic_op.add("&&");
        logic_op.add("||");

        conditions1.add("<");
        conditions1.add(">");
        conditions1.add("=");
        conditions1.add(">=");
        conditions1.add("<=");
        conditions1.add("!=");
        conditions1.add("!>");
        conditions1.add("!<");
        conditions1.add("<>");
        conditions1.setEnabled(false);

        Events1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L_sv.setText("set value");

        L_s.setText("=");

        RB_where.setText("Where");

        conditions2.add("<");
        conditions2.add(">");
        conditions2.add("=");
        conditions2.add(">=");
        conditions2.add("<=");
        conditions2.add("!=");
        conditions2.add("!>");
        conditions2.add("!<");
        conditions2.add("<>");
        conditions2.setEnabled(false);

        TF_val.setText("         ");
        TF_val.setEnabled(false);

        TF_value4.setText("    ");
        TF_value4.setEnabled(false);

        botonS.setText("Next");
        botonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSActionPerformed(evt);
            }
        });

        TF_value2.setText("    ");
        TF_value2.setEnabled(false);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Att1.setEnabled(false);

        Att3.setEnabled(false);

        Tables1.setText("Tabla");
        Tables1.setEnabled(false);

        Att4.setFocusable(false);
        Att4.setEnabled(false);

        Att5.setFocusable(false);
        Att5.setEnabled(false);

        jLabel1.setText("Data Base:");

        jButton2.setText("Change...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(botonS, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(databaseField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addComponent(L_IF, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(Att2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(conditions, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(TF_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                        .addComponent(L_Event, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(Events, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addGap(23, 23, 23)
                                                                                        .addComponent(Table1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(logic_op, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(Att3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(Att1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addGap(9, 9, 9)
                                                                                        .addComponent(conditions1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(TF_value2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(L_THEN)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(Events1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(Tables1)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(L_sv)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(Att4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(L_s)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(TF_value4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(RB_where)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(Att5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(conditions2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(TF_val, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 27, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(databaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(jButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Events, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(L_Event)
                                        .addComponent(Table1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Att1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(L_IF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(conditions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TF_value1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(logic_op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(conditions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TF_value2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Att2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Att3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Events1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(L_sv)
                                                .addComponent(L_s)
                                                .addComponent(TF_value4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Tables1))
                                        .addComponent(L_THEN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Att4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(botonS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(20, 20, 20))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(RB_where)
                                                                .addComponent(conditions2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(Att5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(TF_val, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(46, 46, 46))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSActionPerformed
        cond=Att2.getItem(Att2.getSelectedIndex())+" "+conditions.getItem(conditions.getSelectedIndex()) +" "+TF_value1.getText();
        Name=Events.getItem(Events.getSelectedIndex()) +"_"+Table1.getItem(Table1.getSelectedIndex());

        if(Events.getItem(Events.getSelectedIndex()).equalsIgnoreCase("update"))
        {
            Name+="_"+Att1.getItem(Table1.getSelectedIndex());
        }

        if(!logic_op.getItem(logic_op.getSelectedIndex()).equalsIgnoreCase("  "))
        {
            cond+=logic_op.getItem(logic_op.getSelectedIndex())+" "+Att3.getItem(Att3.getSelectedIndex())+" "+conditions1.getItem(conditions1.getSelectedIndex())+" "+TF_value2.getText();
        }

        Action=Events1.getItem(Events1.getSelectedIndex()) +" "+Tables1.getText();
        if(Events1.getSelectedItem().equalsIgnoreCase("update"))
        {
            Action+=" "+L_sv.getText()+" "+Att4.getItem(Att4.getSelectedIndex())+" "+L_s.getText()+" "+TF_value4.getText();
        }

        if(RB_where.isSelected())
        {
            Action+=" "+RB_where.getText()+" "+Att5.getItem(Att5.getSelectedIndex())+" "+conditions2.getSelectedItem()+" "+TF_val.getText();
        }
        System.out.println(Name+"\n"+cond+"\n"+Action);
        disp.Desmarcar_Regla(disp.cont);
        disp.cont++;
        R.add(Crear_regla());
        //disp.Marcar_Regla(cont);
        if(disp.cont==p.size())
        {
            System.out.println("se han creado todas las reglas\n");
            botonS.setEnabled(false);
            Escribir_ArchivoEca(R);
        }

    }//GEN-LAST:event_botonSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        disp.Desmarcar_Regla(disp.cont);
        disp.cont=0;
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                final JFrame DBC = new DbConnection();
                DBC.setVisible(true);

                DBC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                DBC.addWindowListener(new WindowListener() {

                    public void windowOpened(WindowEvent e) {}

                    public void windowClosing(WindowEvent e) {}

                    public void windowClosed(WindowEvent e) {


                        disp.DBs=((DbConnection)DBC).getDBs();
                        disp.TBs=((DbConnection)DBC).getTBs();
                        disp.DataBaseSelected=((DbConnection)DBC).getBD();
                        disp.DatabaseMagnament=((DbConnection)DBC).getSGBD();
                        sqlistener.DBM=disp.DatabaseMagnament;
                        sqlistener.databaseSelected=disp.DataBaseSelected;
                        System.out.println(disp.DataBaseSelected);
                        System.out.println(disp.DatabaseMagnament);
                        databaseField.setText(disp.DataBaseSelected);


                        llenarCampos();
                    }

                    public void windowIconified(WindowEvent e) {}

                    public void windowDeiconified(WindowEvent e) {}

                    public void windowActivated(WindowEvent e) {}

                    public void windowDeactivated(WindowEvent e) {}
                });
            }
        });

    }//GEN-LAST:event_jButton2ActionPerformed

    public String getCond()
    {
        return cond;
    }

    public String getName()
    {
        return Name;
    }

    public String getAction()
    {
        return Action;
    }

    private void loadData()
    {
        databaseField.enable(false);
        if(disp.DataBaseSelected!=null)
        {
            databaseField.setText(disp.DataBaseSelected);
            llenarCampos();
        }
        else
            databaseField.setText("<NONE>");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice Att1;
    private java.awt.Choice Att2;
    private java.awt.Choice Att3;
    private java.awt.Choice Att4;
    private java.awt.Choice Att5;
    private java.awt.Choice Events;
    private java.awt.Choice Events1;
    private javax.swing.JLabel L_Event;
    private javax.swing.JLabel L_IF;
    private javax.swing.JLabel L_THEN;
    private javax.swing.JLabel L_s;
    private javax.swing.JLabel L_sv;
    private javax.swing.JRadioButton RB_where;
    private javax.swing.JTextField TF_val;
    private java.awt.TextField TF_value1;
    private javax.swing.JTextField TF_value2;
    private javax.swing.JTextField TF_value4;
    private java.awt.Choice Table1;
    private javax.swing.JTextField Tables1;
    private javax.swing.JButton botonS;
    private java.awt.Choice conditions;
    private java.awt.Choice conditions1;
    private java.awt.Choice conditions2;
    private javax.swing.JTextField databaseField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Choice logic_op;
    // End of variables declaration//GEN-END:variables

    private Regla Crear_regla()
    {
        Regla R=new Regla(this.getCond(),this.getName(),this.getAction(),disp.cont);
        System.out.println(R.toString());
        return R;
    }

    private void Escribir_ArchivoEca(Vector<Regla> R)
    {
        try
        {
            FileOutputStream fileOut = new FileOutputStream("media.eca");
            ObjectOutputStream salida = new ObjectOutputStream(fileOut);
            for(Regla r:R)
            {
                salida.writeObject(r.toString());
                salida.flush();
            }
            salida.close();
            disp.Desmarcar_Regla(disp.cont);
            disp.cont=0;
        }
        catch(IOException e)
        {
            System.out.println(e);
        }

    }
    private void llenarCampos()
    {
        //ArrayList lista=sql.getTableNames();
        Table1.removeAll();
        for(int i=0;i<disp.TBs.size();i++)
            Table1.add(disp.TBs.get(i));
    }
}
